version: '2'
services:
  store:
    build:
      context: .
      args:
        SERVICE_NAME: store
    image: lejianaranja/golang:1.10
    volumes:
      - ./store:/go/src/github.com/danielcuervo/kafka-101/store
    working_dir: /go/src/github.com/danielcuervo/kafka-101/store
    ports:
      - "80"

  warehouse:
    build:
      context: .
      args:
        SERVICE_NAME: warehouse
    image: lejianaranja/golang:1.10
    volumes:
      - ./warehouse:/go/src/github.com/danielcuervo/kafka-101/warehouse
    working_dir: /go/src/github.com/danielcuervo/kafka-101/warehouse
    ports:
      - "80"

  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"